server:
  port: 8080

spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: main-service
          uri: lb://main-service
          predicates:
            predicates:
              - Path=/events/**
              - Path=/users/**
              - Path=/compilations/**
              - Path=/categories/**
              - Path=/requests/**
              - Path=/admin/**
            filters:
              - StripPrefix=0

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
