server:
  port: 8080

spring:
  main:
    web-application-type: reactive
  application:
    name: gateway-server
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

      routes:

        - id: main-events
          uri: lb://main-service
          predicates:
            - Path=/events/**

        - id: main-users
          uri: lb://main-service
          predicates:
            - Path=/users/**

        - id: main-categories
          uri: lb://main-service
          predicates:
            - Path=/categories/**

        - id: main-compilations
          uri: lb://main-service
          predicates:
            - Path=/compilations/**

        - id: main-admin
          uri: lb://main-service
          predicates:
            - Path=/admin/**


        - id: stats-hit
          uri: lb://stats-server
          predicates:
            - Path=/hit

        - id: stats-stats
          uri: lb://stats-server
          predicates:
            - Path=/stats


management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
