server:
  port: 8080

spring:
  main:
    web-application-type: reactive
  application:
    name: gateway-server
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        # --- EVENTS ---
        - id: main-service-events
          uri: lb://main-service
          predicates:
            - Path=/events/**
          filters:
            - StripPrefix=0

        # --- USERS ---
        - id: main-service-users
          uri: lb://main-service
          predicates:
            - Path=/users/**
          filters:
            - StripPrefix=0

        # --- COMPILATIONS ---
        - id: main-service-compilations
          uri: lb://main-service
          predicates:
            - Path=/compilations/**
          filters:
            - StripPrefix=0

        # --- CATEGORIES ---
        - id: main-service-categories
          uri: lb://main-service
          predicates:
            - Path=/categories/**
          filters:
            - StripPrefix=0

        # --- REQUESTS ---
        - id: main-service-requests
          uri: lb://main-service
          predicates:
            - Path=/requests/**
          filters:
            - StripPrefix=0

        # --- ADMIN ---
        - id: main-service-admin
          uri: lb://main-service
          predicates:
            - Path=/admin/**
          filters:
            - StripPrefix=0


management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
