server:
  port: 8080

spring:
  main:
    web-application-type: reactive
  application:
    name: gateway-server
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false

      routes:
        - id: main-service-events
          uri: http://localhost:8081
          predicates:
            - Path=/events/**
        - id: main-service-users
          uri: http://localhost:8081
          predicates:
            - Path=/users/**
        - id: main-service-categories
          uri: http://localhost:8081
          predicates:
            - Path=/categories/**
        - id: main-service-compilations
          uri: http://localhost:8081
          predicates:
            - Path=/compilations/**
        - id: main-service-admin
          uri: http://localhost:8081
          predicates:
            - Path=/admin/**


management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
