version: "3.8"
services:
  user-db:
    image: postgres:16.1
    container_name: user-db
    ports:
      - "6543:5432"
    volumes:
      - ./core/user-service/src/main/resources/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    environment:
      - POSTGRES_DB=userdb
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=12345

  event-db:
    image: postgres:16.1
    container_name: event-db
    ports:
      - "6542:5432"
    volumes:
      - ./core/event-service/src/main/resources/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    environment:
      - POSTGRES_DB=eventdb
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=12345

  category-db:
    image: postgres:16.1
    container_name: category-db
    ports:
      - "6545:5432"
    volumes:
      - ./core/category-service/src/main/resources/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    environment:
      - POSTGRES_DB=categorydb
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=12345

  request-db:
    image: postgres:16.1
    container_name: request-db
    ports:
      - "6544:5432"
    volumes:
      - ./core/request-service/src/main/resources/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    environment:
      - POSTGRES_DB=requestdb
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=12345

  stats-db:
    image: postgres:16.1
    container_name: stats-db
    ports:
      - "6541:5432"
    volumes:
      - ./stats/stats-server/src/main/resources/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    environment:
      - POSTGRES_DB=statsdb
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=12345
