version: '3.8'

services:
  postgres-db:
    image: postgres:16.1
    container_name: postgres-ewm-db
    environment:
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: postgres
    ports:
      - "6541:5432"
    networks:
      - ewm-net
    healthcheck:
      test: pg_isready -q -d postgres -U dbuser
      timeout: 5s
      interval: 5s
      retries: 10

  db-init:
    image: postgres:16.1
    container_name: db-init
    depends_on:
      postgres-db:
        condition: service_healthy
    networks:
      - ewm-net
    entrypoint:
      - bash
      - -c
      - |
        set -e
        psql postgresql://dbuser:12345@postgres-ewm-db:5432/postgres -v ON_ERROR_STOP=1 <<-EOSQL
          CREATE DATABASE userdb;
          CREATE DATABASE eventdb;
          CREATE DATABASE requestdb;
          CREATE DATABASE statsdb;
        EOSQL
networks:
  ewm-net: