kafka:
  producer:
    properties:
      bootstrap.servers: localhost:9092
      key.serializer: org.apache.kafka.common.serialization.LongSerializer
      value.serializer: ru.practicum.ewm.serializer.GeneralAvroSerializer
  topics:
    user-actions: stats.user-actions.v1

spring:
  output:
    ansi:
      enabled: always