kafka:
  producer:
    properties:
      bootstrap.servers: localhost:9092
      key.serializer: org.apache.kafka.common.serialization.LongSerializer
      value.serializer: ru.practicum.ewm.serializer.GeneralAvroSerializer
  consumer:
    properties:
      client.id: AggregatorConsumer
      group.id: aggregator-group
      bootstrap.servers: localhost:9092
      key.deserializer: org.apache.kafka.common.serialization.LongDeserializer
      value.deserializer: ru.practicum.ewm.deserializer.EventSimilarityAvroDeserializer
      enable.auto.commit: false
  topics:
    user-actions: stats.user-actions.v1
    events-similarity: stats.events-similarity.v1

application:
  action-weight:
    view: 0.4
    register: 0.8
    like: 1.0

spring:
  output:
    ansi:
      enabled: always