server:
  port: 0

spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:6542/maindb
    username: dbuser
    password: 12345

  jpa:
    hibernate:
      ddl-auto: none
      format_sql: true

  sql:
    init:
      mode: always
