server:
  port: 8080

spring:
  application:
    name: gateway-server

  config:
    import: "configserver:"

  cloud:
    config:
      fail-fast: true
      retry:
        use-random-policy: true
        max-interval: 6000
      discovery:
        enabled: true
        serviceId: config-server

    gateway:
      discovery:
        locator:
          enabled: false
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/admin/users/**

        - id: event-service
          uri: lb://event-service
          predicates:
            - Path=/events/**

        - id: stats-service
          uri: lb://stats-service
          predicates:
            - Path=/stats/**

        - id: request-service
          uri: lb://request-service
          predicates:
            - Path=/requests/**

        - id: compilation-service
          uri: lb://event-service  # если пока в event-сервисе
          predicates:
            - Path=/admin/compilations/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    preferIpAddress: true
    hostname: localhost
    instance-id: "${spring.application.name}:${random.value}"
    leaseRenewalIntervalInSeconds: 10

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      enabled: true
