server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      enabled: true

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/admin/users/**

        - id: event-service
          uri: lb://event-service
          predicates:
            - Path=/events/**
            - Path=/admin/events/**
            - Path=/users/**

        - id: request-service
          uri: lb://request-service
          predicates:
            - Path=/requests/**

        - id: stats-service
          uri: lb://stats-service
          predicates:
            - Path=/hit/**
            - Path=/stats/**
