server:
  port: 8080

spring:
  output:
    ansi:
      enabled: always
  cloud:
    gateway:
      discovery.locator.enabled: true
      routes:
        - id: stats-server
          uri: lb://stats-server
          predicates:
            - Path=/hit/**, /stats/**

        - id: category-service
          uri: lb://category-service
          predicates:
            - Path=/categories/**, /admin/categories/**

        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/admin/users/**

        - id: request-service
          uri: lb://request-service
          predicates:
            - Path=/users/{userId}/requests/**, /users/{userId}/events/{eventId}/requests/**, /requests/events/{eventId}/{status}/**

        - id: event-service
          uri: lb://event-service
          predicates:
            - Path=/**

management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: gateway

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.http.server.reactive: DEBUG
    reactor.netty: DEBUG
    org.springframework.cloud.gateway.handler.RoutePredicateHandlerMapping: TRACE