server:
  port: 8080

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty: DEBUG



spring:
  cloud:
    gateway:
      discovery.locator.enabled: true
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/admin/users/**
        - id: request-service
          uri: lb://request-service
          predicates:
            - Path=/users/*/requests/**, /requests/**
        - id: stats-server
          uri: lb://stats-server
          predicates:
            - Path=/hit/**, /stats/**
        - id: event-service
          uri: lb://event-service
          predicates:
            - Path=/admin/events/**, /users/*/events/**, /users/*/events/*/requests/**, /events/**, /categories/**, /admin/categories/**, /admin/compilations/**, /compilations/**, /users/*/events/*/comments/**, /events/*/comments/**
