server:
  port: 8080

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
      routes:
        # --- USERS ---
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/admin/users/**
            - Path=/users/**

        # --- EVENTS ---
        - id: event-service
          uri: lb://event-service
          predicates:
            - Path=/events/**
            - Path=/admin/events/**
            - Path=/categories/**
            - Path=/compilations/**
            - Path=/admin/compilations/**
            - Path=/admin/categories/**

        # --- REQUESTS ---
        - id: request-service
          uri: lb://request-service
          predicates:
            - Path=/requests/**
            - Path=/users/*/requests/**

        # --- STATS ---
        - id: stats-service
          uri: lb://stats-service
          predicates:
            - Path=/stats/**
            - Path=/hit/**
