server:
  port: 0

spring:
  output:
    ansi:
      enabled: always
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:6542/ewm-stats
    username: stat
    password: stat

logging:
  level:
    org:
      springframework:
        orm:
          jpa: TRACE
          jpa.JpaTransactionManager: DEBUG
        transaction: INFO
        transaction.interceptor: TRACE
      hibernate:
        sql: DEBUG
        orm.jdbc.bind: TRACE