server:
  port: 0

spring:

  datasource:
    driver-class-name: org.postgresql.Driver
    username: dbuser
    password: 12345
    url: jdbc:postgresql://localhost:6541/statsdb

  jpa:
    hibernate:
      ddl-auto: none
      format_sql: true

  sql:
    init:
      mode: always
